language: node_js
os: linux
node_js:
  - "14.18.1"
dist: xenial
addons:
  chrome: stable
branches:
  - master
  - build-debug
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng test
  - npm run deploy:gh-pages
# deploy:
#   strategy: git
#   provider: pages
#   github_token: $public_repo
#   local_dir: docs/twitter-angular-clone.github.io
#   on:
#     branch: master
