---
version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.2.3

executors:
  angular-build:
    docker:
      - image: talktotrev/angular-test:1.0.0
        user: circleci
    working_directory: /home/circleci/project

jobs:
  setup:
    executor: angular-build
    working_directory: /home/circleci/project/src
    steps:
      - checkout:
          path: /home/circleci/project/src
      - node/install-packages:
          pkg-manager: npm
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .cache/puppeteer
            - src
  npm-cli:
    executor: angular-build
    working_directory: /home/circleci/project/src
    parameters:
      message:
        type: string
      command:
        type: string
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          shell: /bin/bash -exo pipefail -lc
          name: << parameters.message >>
          command: << parameters.command >>
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .cache/puppeteer
            - src
  codecov:
    executor: angular-build
    working_directory: /home/circleci/project/src
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - codecov/upload
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .cache/puppeteer
            - src
  local-build:
    working_directory: /home/circleci/project
    docker:
      - image: angular-test:latest
    steps:
      - checkout
      - run:
          shell: /bin/bash -exo pipefail -lc
          name: NPM install
          command: npm i
      - run:
          shell: /bin/bash -exo pipefail -lc
          name: Lint Check Typescript Files
          command: npm run lint
      - run:
          shell: /bin/bash -exo pipefail -lc
          name: Compile Typescript and SASS
          command: npm run build
      - run:
          shell: /bin/bash -exo pipefail -lc
          name: Run Unit and End to End Tests
          command: npm run test
  pages-build:
    working_directory: /home/circleci/project/src
    executor: angular-build
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - add_ssh_keys:
          fingerprints:
            - '00:d0:ec:83:70:ec:78:07:91:60:3b:69:a7:40:08:a3'
      - run:
          name: Adding Github to Known Hosts File
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Adding Github Pages NPM Package
          command: npm install gh-pages@2.0.1
      - run:
          name: Configure CI git user email
          command: git config user.email "ci-build@nowhere.net"
      - run:
          name: Configure CI git user name
          command: git config user.name "ci-build"
      - run:
          name: Build and Deploy to Github Pages Branch
          command: npm run gh-pages:build

workflows:
  version: 2
  circleci-build:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - develop
                - /features/.*/
                - /feature/.*/
                - /dependabot/.*/
                - pkg-update
                - pkg-updates
      - npm-cli:
          name: lint
          message: Lint Check Typescript Files
          command: npm run lint
          requires:
            - setup
      - npm-cli:
          name: compile
          message: Compile Typescript and SASS
          command: npm run build
          requires:
            - setup
      - npm-cli:
          name: unit-test
          message: Run Unit and End to End Tests
          command: npm run test-cli
          requires:
            - lint
      - codecov:
          requires:
            - unit-test
  local-cli-build:
    jobs:
      - local-build:
          filters:
            branches:
              ignore: /.*/
  gh-pages:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
      - npm-cli:
          name: lint
          message: Lint Check Typescript Files
          command: npm run lint
          requires:
            - setup
      - npm-cli:
          name: compile
          message: Compile Typescript and SASS
          command: npm run build
          requires:
            - setup
      - npm-cli:
          name: unit-test
          message: Run Unit and End to End Tests
          command: npm run test-cli
          requires:
            - lint
      - pages-build:
          requires:
            - unit-test
