# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7
  codecov: codecov/codecov@3.1.1

executors:
  angular-build:
    docker:
      - image: talktotrev/angular-build:1.0
    working_directory: /root/project

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  setup:
    executor: angular-build
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - persist_to_workspace:
          root: /root/project
          paths: 
            - ./
  npm-cli:
    executor: angular-build
    parameters:
      message:
        type: string
      command:
        type: string
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /root/project
      - run:
          name: << parameters.message >>
          command: << parameters.command >>
  codecov:
    executor: angular-build
    steps:
      - codecov/upload

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the jobs above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  complete-build:
    jobs:
      - setup
      - npm-cli:
          message: Run lint
          command: npm run lint
          requires: 
            - setup
      - npm-cli:
          message: Compile Typescript and SASS
          command: npm run build
          requires: 
            - setup
      - npm-cli:
          message: Run Unit and End to End Tests
          command: npm run test-cli
          requires: 
            - setup
      - codecov
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
