---

name: Angular Ng Update
#on:
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '*/5 * * * *'

on: 
  push:
    branches:
      - 'master'

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  checks: read


env:
  TARGET_BRANCH: 'master'
  PR_BRANCH: 'dependabot/ng-update'
  PR_AUTHOR: 'dependabot[bot]'

jobs:
  detect-update:
    runs-on: ubuntu-latest
    outputs:
      REQUIRE_UPDATE: ${{ steps.required_updates.outputs.REQUIRE_UPDATE }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: npm-install
        run: npm install
      - id: required_updates
        run: |
          AVAIL_UPDATE=`npx ng update | grep 'packages to update' | wc -l | tr -d ' ' | tr -d '\n'` &&
          AVAILABLE_UPDATE=`if [[ $AVAIL_UPDATE == 0 ]]; then echo 'false'; else echo 'true'; fi` &&
          #echo $AVAILABLE_UPDATE && 
          #echo "AVAILABLE_UPDATE=$AVAIL_UPDATE" >> "$GITHUB_ENV" &&
          CORRECT_BRANCH='${{ env.TARGET_BRANCH == github.ref_name }}' && 
          #echo $CORRECT_BRANCH && 
          #echo "CORRECT_BRANCH=$CORRECT_BRANCH" >> "$GITHUB_ENV" &&
          REQUIRE_UPDATE=`if [[ $AVAILABLE_UPDATE == 'true' &&  $CORRECT_BRANCH == 'true' ]]; then echo 'true'; else echo 'false'; fi` &&
          #echo $REQUIRE_UPDATE &&
          echo "REQUIRE_UPDATE=$REQUIRE_UPDATE" >> "$GITHUB_OUTPUT"
  ng-update:
    if: ${{ needs.detect-update.outputs.REQUIRE_UPDATE == 'true' }}
    needs: detect-update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: git setup
        uses: actions4git/setup-git@v1
      - name: Create NG Update Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.PR_BRANCH }} 
      - name: Update Angular CLI and Angular Core
        run: |
          npm update @angular/cli && 
          npx ng update @angular/core
      - name: git add, commit, and push
        run: |
          git add . && 
          git commit -m 'chore: angular core and cli updates' &&
          git push --force origin ${{ env.PR_BRANCH }} 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author: ${{ env.PR_AUTHOR }}
          branch: ${{ env.PR_BRANCH }} 
    
#  ng-update:
#    runs-on: ubuntu-latest
#    if: github.env.SHOULD_RUN == true
#    steps:
#      - name: Echo Test
#        run: echo "should run!" && echo ${{ toJson(github.env) }}
      #- name: Create NG Update Branch
      #  uses: peterjgrainger/action-create-branch@v2.2.0
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    branch: 'features/ng-update'
      #- name: Update Angular CLI
      #  run: npm update @angular/cli
      #- name: Angular Core
      #  run: npx ng update @angular/core
