---  
name: "NG Version Update"

on:
  schedule:
    - cron: 0,15,30,45 * * * *

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - id: ng-update
        name: Updating ng dependencies # the magic happens here !
        uses: tinesoft/ngx-uptodate@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Label the ng pull request
        run: |
          echo ${{ steps.ng-update.outputs.pr-number }}