---
# Third Party Workflows used:
#   1.  actions/checkout@v4 - https://github.com/marketplace/actions/checkout
#   2.  actions4git/setup-git@v1 - https://github.com/marketplace/actions/add-commit-and-push
#   3.  peterjgrainger/action-create-branch@v3.0.0 - https://github.com/marketplace/actions/create-branch
#   4.  peter-evans/create-pull-request@v6 - https://github.com/marketplace/actions/create-pull-request
#
#  Configure allowed actions here: https://github.com/mcknasty/twitter-angular-clone.github.io/settings/actions
#
#  steps context reference - https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
#  needs context reference - https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
#  output reference - https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
#  
#

name: Angular Core Update
#on:
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '*/5 * * * *'

on: 
  push:
    branches:
      - 'master'

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  checks: read


env:
  TARGET_BRANCH: 'master'
  PR_BRANCH: 'dependabot/ng-update'
  PR_AUTHOR: 'dependabot[bot] dependabot[bot]@users.noreply.github.com'

jobs:
  detect-update:
    runs-on: ubuntu-latest
    outputs:
      # the steps key on this context requires the use of the 'id' key, not 'name'
      REQUIRE_UPDATE: ${{ steps.required_updates.outputs.REQUIRE_UPDATE }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: git setup
        uses: actions4git/setup-git@v1
      - name: Create NG Update Branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout and pull branch
        run: |
          git checkout -b ${{ env.TARGET_BRANCH }} &&
          git pull origin ${{ env.TARGET_BRANCH }}
      - id: npm-install
        run: npm install --silent --no-progress
# This was a pain to get right.  Need to swap name key with id key to use the steps context variable
# outputing was variables was difficult as well.        
      - id: required_updates
        run: |
          AVAIL_UPDATE=`npx ng update | grep 'packages to update' | wc -l | tr -d ' ' | tr -d '\n'` &&
          AVAILABLE_UPDATE=`if [[ $AVAIL_UPDATE == 0 ]]; then echo 'false'; else echo 'true'; fi` &&
          CORRECT_BRANCH='${{ env.TARGET_BRANCH == github.ref_name }}' && 
          REQUIRE_UPDATE=`if [[ $AVAILABLE_UPDATE == 'true' &&  $CORRECT_BRANCH == 'true' ]]; then echo 'true'; else echo 'false'; fi` &&
          echo "REQUIRE_UPDATE=$REQUIRE_UPDATE" >> "$GITHUB_OUTPUT"
  ng-update:
    if: ${{ needs.detect-update.outputs.REQUIRE_UPDATE == 'true' }}
    needs: detect-update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: git setup
        uses: actions4git/setup-git@v1
      - name: Create NG Update Branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run npm install
        run: npm install --silent --no-progress
      - name: Update Angular CLI
        run: |
          npm update @angular/cli --silent --no-progress &&
          git add . && 
          git commit -m 'chore: angular cli updates'
      - name: Update Angular Core
        run: |
          npx ng update @angular/core
          git add . && 
          git commit -m 'chore: angular core updates'
      - name: git push
        run: |
          git checkout -b ${{ env.PR_BRANCH }}
          git push --force origin ${{ env.PR_BRANCH }} 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author: ${{ env.PR_AUTHOR }}
          branch: ${{ env.TARGET_BRANCH }} 
